# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/

AllCops:
  TargetRubyVersion: 2.4

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/MutableConstant:
  Enabled: false

Style/GuardClause:
  Enabled: false
